version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:${MINIO_PORT}"
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
