version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
    command: server /data
